### ISSUE TITLE
Delete traffic from referral doesn't work

### ISSUE THREAD

**Issue by alinacsava** [simpleanalytics/roadmap#405]
Throws the "Oops something went wrong" error

<img width="703" alt="Screenshot 2020-09-15 at 18 51 18" src="https://user-images.githubusercontent.com/5655500/93245761-0df71480-f78c-11ea-913a-997015ddade0.png">

**Comment by adriaanvanrossum** [comment]
This issue has been fixed now. Thanks for reporting.

**Comment by alinacsava** [comment]
Now the deleting page shows ok, but unfortunately deleting the visits still doesn't work. I get the error "Can't delete your visits, please contact support."

<img width="740" alt="Screenshot 2020-09-22 at 23 00 04" src="https://user-images.githubusercontent.com/5655500/93937219-aa3e8f80-fd27-11ea-9c96-b1e6ec16f767.png">

**Comment by adriaanvanrossum** [comment]
Thanks! Could you try again? Deployed another fix, haha.

**Comment by alinacsava** [comment]
Deleted successfully. All good now, thanks!
